CREATE OR REPLACE PACKAGE types
AS
    TYPE ref_cursor IS REF CURSOR;
END;
/
CREATE OR REPLACE FUNCTION SELECT_GROUPS_ID_NAMES
RETURN types.ref_cursor
AS
    groups_cursor types.ref_cursor;
BEGIN
    OPEN groups_cursor FOR
        SELECT g.GROUP_ID as "GROUP_ID", GET_GROUP_NAME(g.GROUP_NAME) as "GROUP_NAME"
        FROM GROUPS g;
    RETURN groups_cursor;
END;
/
CREATE OR REPLACE FUNCTION SELECT_STUDENTS
RETURN types.ref_cursor
AS
    students_cursor types.ref_cursor;
BEGIN
    OPEN students_cursor FOR
        SELECT p.PEOPLE_ID, p.LAST_NAME, p.FIRST_NAME, p.PATHER_NAME, p.GROUP_ID
        FROM PEOPLE p
        WHERE p.PEOPLE_TYPE = 'S';
    RETURN students_cursor;
END;
/
CREATE OR REPLACE FUNCTION SELECT_STUDENT (
    STUDENT_ID INTEGER
)
RETURN types.ref_cursor
AS
    students_cursor types.ref_cursor;
BEGIN
    OPEN students_cursor FOR
        SELECT p.PEOPLE_ID, p.LAST_NAME, p.FIRST_NAME, p.PATHER_NAME, 
        p.GROUP_ID as "GROUP_ID", GET_GROUP_NAME(g.GROUP_NAME) as "GROUP_NAME"
        FROM PEOPLE p
        JOIN GROUPS g ON g.GROUP_ID = p.GROUP_ID
        WHERE p.PEOPLE_ID = STUDENT_ID;
    RETURN students_cursor;
END;
/
CREATE OR REPLACE PROCEDURE INSERT_STUDENT (
    LAST_NAME_PARAMETER VARCHAR,
    FIRST_NAME_PARAMETER VARCHAR,   
    PATHER_NAME_PARAMETER VARCHAR,
    GROUP_ID_PARAMETER INTEGER
)
IS
BEGIN
    INSERT INTO PEOPLE
    (FIRST_NAME, LAST_NAME, PATHER_NAME, GROUP_ID, PEOPLE_TYPE)
    VALUES
    (FIRST_NAME_PARAMETER, LAST_NAME_PARAMETER, PATHER_NAME_PARAMETER, GROUP_ID_PARAMETER,'S');
END;
/
CREATE OR REPLACE PROCEDURE UPDATE_STUDENT (
    STUDENT_ID_PARAMETER INTEGER,
    LAST_NAME_PARAMETER VARCHAR,
    FIRST_NAME_PARAMETER VARCHAR,  
    PATHER_NAME_PARAMETER VARCHAR,
    GROUP_ID_PARAMETER INTEGER
)
IS
BEGIN
    UPDATE PEOPLE p
    SET p.FIRST_NAME = FIRST_NAME_PARAMETER,
        p.LAST_NAME = LAST_NAME_PARAMETER,
        p.PATHER_NAME = PATHER_NAME_PARAMETER,
        p.GROUP_ID = GROUP_ID_PARAMETER
    WHERE p.PEOPLE_ID = STUDENT_ID_PARAMETER;
END;
/
CREATE OR REPLACE PROCEDURE DELETE_STUDENT (
    STUDENT_ID_PARAMETER INTEGER
)
IS
BEGIN
    DELETE
    FROM PEOPLE p
    WHERE p.PEOPLE_ID = STUDENT_ID_PARAMETER;
END;
/